### ISSUE TITLE
Damage Meter window doesn't appear when enabled

### ISSUE THREAD

**Issue by yeroca** [kauffman12/EQLogParser#341]
**Describe the bug**

I'm on Windows 11 with the eqlp 2.3.36
I have selected my character's log file on the beta server, and I can see damage showing there in its recent history, but if I go to View-> Enable Damage Meter, and click it, I was expecting to see a floating window pop up, but there's no pop up at all.  I tried exiting eqlp, deleting the settings.txt in my users/username/appdata/roaming/eqlogparser/config/  then restarting, but I still can't get the damage meter to pop up.

**To Reproduce**
1. Go to View
2.  click on enable damage meter
3. Notice no damage meter

**Expected behavior**
I expected a floating damage meter to pop up, looking like the one in the damage meter setup

**Screenshots**
A screenshot of nothing wouldn't help much, I'm afraid.

**Comment by kauffman12** [comment]
Can you configure the damage meter and save a new position for it and see if that helps?

**Comment by kauffman12** [comment]
As long as the menu gives you the Disable option it should be on and if you're seeing the Fight List populating with NPCs it should be working. I haven't seen anyone else would this problem yet.

**Comment by yeroca** [comment]
I thought maybe having two joined monitors with unequal resolution might be affecting it, so I disabled one monitor, and the problem persists. 

Let me know if there are any other experiments you want me try.

**Comment by kauffman12** [comment]
Try this build. It's got some debug statements that might help. Try kill stuff with overlay enabled and then see what's in the log.

https://github.com/kauffman12/EQLogParser/raw/master/Release/test/EQLogParser-install-2.3.36-test1.exe

**Comment by yeroca** [comment]
Ah, it was my misunderstanding.  I thought the window would be up even when there are no NPCs engaged.

**Comment by yeroca** [comment]
> Try this build. It's got some debug statements that might help. Try kill stuff with overlay enabled and then see what's in the log.
> 
> https://github.com/kauffman12/EQLogParser/raw/master/Release/test/EQLogParser-install-2.3.36-test1.exe

Thanks for creating this test version, but I didn't see it until I kinda figured out I needed to engage for the window to appear.
